server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.68.98:3306/nyang?serverTimezone=Asia/Seoul
    username: nyang
    password: dr420138!
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
