server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.233.129:3306/nyang?serverTimezone=Asia/Seoul
    username: nyang
    password: dr420138!
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

apple:
  team:
    id: YYZ32L49X6
  login:
    key: P5UR7W5F7L
  client:
    id: com.ssafy.CatMap
  redirect:
    url: https://wenail.co.kr/apple/callback
  key:
    path: /home/ubuntu/key/AuthKey_P5UR7W5F7L.p8